#!/usr/bin/env node
/**
 * One-off correction for the 1206 products already imported by import.mjs
 * BEFORE it applied Bulgaria's 20% VAT. PrestaShop's ps_product.price is
 * stored without tax, but topstyle.bg's storefront shows prices WITH the
 * 20% VAT already added - so every priceEur/priceBgn currently in our DB is
 * ~16.7% too low (e.g. windbreaker SKU 2383: stored 47.49, real site price
 * 56.99 = 47.49 * 1.2).
 *
 * This script multiplies every product's current priceEur by 1.2 (undoing
 * nothing else), recomputes priceBgn from the corrected priceEur, and does
 * this directly against the live Neon/Postgres DB. It also writes a matching
 * MySQL UPDATE file for php-site.
 *
 * Safe to run exactly ONCE. Do NOT run this again after re-running
 * import.mjs (which now applies VAT itself going forward) - doing so would
 * apply VAT twice. This script checks a marker file to guard against
 * accidental double-runs.
 *
 * RUN: node scripts/prestashop-import/fix-vat.mjs
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = path.resolve(__dirname, "..", "..");
const OUT_SQL = path.join(__dirname, "mysql-fix-vat.sql");
const MARKER = path.join(__dirname, ".vat-fix-applied");

function loadEnvFile() {
  const envPath = path.join(PROJECT_ROOT, ".env");
  if (!fs.existsSync(envPath)) return;
  const text = fs.readFileSync(envPath, "utf8");
  for (const line of text.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    if (!(key in process.env)) process.env[key] = value;
  }
}
loadEnvFile();

const { PrismaClient } = await import("@prisma/client");
const prisma = new PrismaClient();

const VAT_RATE = 1.2;
const EUR_TO_BGN = 1.95583;

function sqlStr(v) {
  if (v === null || v === undefined) return "NULL";
  return `'${String(v).replace(/\\/g, "\\\\").replace(/'/g, "\\'")}'`;
}

async function withRetry(fn, { attempts = 5, baseDelayMs = 1500 } = {}) {
  let lastErr;
  for (let i = 0; i < attempts; i++) {
    try {
      return await fn();
    } catch (err) {
      lastErr = err;
      const transient =
        err?.code === "P1017" ||
        err?.code === "P1001" ||
        err?.code === "P1002" ||
        /closed the connection|connection.*(reset|terminated|lost)/i.test(String(err?.message || ""));
      if (!transient || i === attempts - 1) throw err;
      const delay = baseDelayMs * Math.pow(2, i);
      console.warn(`  (connection hiccup, retrying in ${delay}ms - attempt ${i + 2}/${attempts})`);
      await new Promise((r) => setTimeout(r, delay));
    }
  }
  throw lastErr;
}

async function main() {
  if (fs.existsSync(MARKER)) {
    console.error(
      `Refusing to run: ${MARKER} already exists, meaning this fix was already applied once.\n` +
        `If you really need to re-run it (e.g. you manually reverted prices), delete that file first.`
    );
    process.exit(1);
  }

  const products = await prisma.product.findMany({ select: { id: true, sku: true, priceEur: true } });
  console.log(`Found ${products.length} products. Applying 20% VAT correction...`);

  const sql = [
    "-- Generated by scripts/prestashop-import/fix-vat.mjs - one-off VAT correction, run ONCE.",
    "SET NAMES utf8mb4;",
    "",
  ];

  let updated = 0;
  for (const prod of products) {
    const newPriceEur = Math.round(prod.priceEur * VAT_RATE * 100) / 100;
    const newPriceBgn = Math.round(newPriceEur * EUR_TO_BGN * 100) / 100;

    await withRetry(() =>
      prisma.product.update({
        where: { id: prod.id },
        data: { priceEur: newPriceEur, priceBgn: newPriceBgn },
      })
    );
    updated++;
    if (updated % 100 === 0) console.log(`  ...${updated} products updated so far`);

    sql.push(
      `UPDATE product SET price_eur = ${newPriceEur}, price_bgn = ${newPriceBgn} WHERE sku = ${sqlStr(prod.sku)};`
    );
  }

  fs.writeFileSync(OUT_SQL, sql.join("\n"), "utf8");
  fs.writeFileSync(MARKER, new Date().toISOString(), "utf8");

  console.log(`\nDone. Corrected VAT on ${updated} products in the live Next.js database.`);
  console.log(`MySQL update file written to: ${OUT_SQL}`);
  console.log(`Run that file against php-site's MySQL DB whenever it's live.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
